# Generated by Django 5.0.6 on 2026-08-30 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_model_n_74ab63_idx",
            old_name="audit_model_object_created_idx",
        ),
    ]
