# Generated by Django 5.0.6 on 2026-08-30 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idempotency", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="idempotency_expires_a43cec_idx",
            old_name="idempotency_expires_at_idx",
        ),
    ]
